---
steps:
- name: python:3.9
  id: 'install dependencies'
  entrypoint: python3
  args: 
  - '-m'
  - 'pip'
  - 'install'
  - '-r'
  - 'back-end/requirements.txt'
- name: python:3.9
  entrypoint: python3
  id: 'run test'
  args:
  - '-m'
  - 'test'
  - '-v'
  - './back-end/'
  - 'test.py'
... 
