---
steps:
- name: python:3.9
  id: 'install dependencies'
  entrypoint: python3
  args: 
  - '-m'
  - 'pip'
  - 'install'
  - '-r'
  - 'back-end/requirements.txt'
  - '--user'
- name: python3.9
  id: 'install mockfirestore'
  entrypoint: python3
  args:
  - 'pip'
  - 'install'
  - 'mock-firestore'
- name: python:3.9
  entrypoint: python3
  id: 'run test'
  args:
  - 'back-end/test.py'
  waitFor:
  - 'install dependencies'
  - 'install mockfirestore'
... 
